
package Sudoku;

/**
 *
 * @author Ashfia
 */
import javax.swing.JButton;
import javax.swing.JPanel;

/* 
 * This class creates the JPanel for the inputs window
 * It contains a constructor to remove buttons according to the selected level
 * And some methods to give functionality to the input buttons
 */
public class InputsUI extends javax.swing.JPanel {
    private SudokuUI sudokuUI;
    private JPanel block;
    private JButton inputButton;
    private int numOfInputs;
    
    public InputsUI(SudokuUI sudokuUI, JPanel block, JButton inputButton, int numOfInputs) {
        this.sudokuUI = sudokuUI;
        this.block = block;
        this.inputButton = inputButton;
        this.numOfInputs = numOfInputs;
        initComponents();
        if(numOfInputs == 4) {
            this.remove(five);
            this.remove(six);
            this.remove(seven);
            this.remove(eight);
            this.remove(nine);
            this.remove(ten);
            this.remove(eleven);
            this.remove(twelve);
            this.remove(thirteen);
            this.remove(fourteen);
            this.remove(fifteen);
            this.remove(sixteen);
        }
        else if(numOfInputs == 9){
            nine.setLocation(480, 0);
            this.remove(ten);
            this.remove(eleven);
            this.remove(twelve);
            this.remove(thirteen);
            this.remove(fourteen);
            this.remove(fifteen);
            this.remove(sixteen);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        six = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        eleven = new javax.swing.JButton();
        twelve = new javax.swing.JButton();
        thirteen = new javax.swing.JButton();
        fifteen = new javax.swing.JButton();
        sixteen = new javax.swing.JButton();
        fourteen = new javax.swing.JButton();

        setLayout(null);

        one.setBackground(new java.awt.Color(255, 255, 255));
        one.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        one.setText("1");
        one.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        add(one);
        one.setBounds(0, 0, 60, 60);

        two.setBackground(new java.awt.Color(255, 255, 255));
        two.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        two.setText("2");
        two.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        add(two);
        two.setBounds(60, 0, 60, 60);

        three.setBackground(new java.awt.Color(255, 255, 255));
        three.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        three.setText("3");
        three.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        add(three);
        three.setBounds(120, 0, 60, 60);

        four.setBackground(new java.awt.Color(255, 255, 255));
        four.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        four.setText("4");
        four.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        add(four);
        four.setBounds(180, 0, 60, 60);

        five.setBackground(new java.awt.Color(255, 255, 255));
        five.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        five.setText("5");
        five.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        add(five);
        five.setBounds(240, 0, 60, 60);

        seven.setBackground(new java.awt.Color(255, 255, 255));
        seven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        seven.setText("7");
        seven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        add(seven);
        seven.setBounds(360, 0, 60, 60);

        eight.setBackground(new java.awt.Color(255, 255, 255));
        eight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eight.setText("8");
        eight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        add(eight);
        eight.setBounds(420, 0, 60, 60);

        nine.setBackground(new java.awt.Color(255, 255, 255));
        nine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nine.setText("9");
        nine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        add(nine);
        nine.setBounds(0, 60, 60, 60);

        six.setBackground(new java.awt.Color(255, 255, 255));
        six.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        six.setText("6");
        six.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        add(six);
        six.setBounds(300, 0, 60, 60);

        ten.setBackground(new java.awt.Color(255, 255, 255));
        ten.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ten.setText("10");
        ten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });
        add(ten);
        ten.setBounds(60, 60, 60, 60);

        eleven.setBackground(new java.awt.Color(255, 255, 255));
        eleven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eleven.setText("11");
        eleven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        eleven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevenActionPerformed(evt);
            }
        });
        add(eleven);
        eleven.setBounds(120, 60, 60, 60);

        twelve.setBackground(new java.awt.Color(255, 255, 255));
        twelve.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        twelve.setText("12");
        twelve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        twelve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveActionPerformed(evt);
            }
        });
        add(twelve);
        twelve.setBounds(180, 60, 60, 60);

        thirteen.setBackground(new java.awt.Color(255, 255, 255));
        thirteen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        thirteen.setText("13");
        thirteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        thirteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirteenActionPerformed(evt);
            }
        });
        add(thirteen);
        thirteen.setBounds(240, 60, 60, 60);

        fifteen.setBackground(new java.awt.Color(255, 255, 255));
        fifteen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fifteen.setText("15");
        fifteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        fifteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fifteenActionPerformed(evt);
            }
        });
        add(fifteen);
        fifteen.setBounds(360, 60, 60, 60);

        sixteen.setBackground(new java.awt.Color(255, 255, 255));
        sixteen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sixteen.setText("16");
        sixteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        sixteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixteenActionPerformed(evt);
            }
        });
        add(sixteen);
        sixteen.setBounds(420, 60, 60, 60);

        fourteen.setBackground(new java.awt.Color(255, 255, 255));
        fourteen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fourteen.setText("14");
        fourteen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 112, 186)));
        fourteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourteenActionPerformed(evt);
            }
        });
        add(fourteen);
        fourteen.setBounds(300, 60, 60, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_nineActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_tenActionPerformed

    private void elevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_elevenActionPerformed

    private void twelveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_twelveActionPerformed

    private void thirteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirteenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_thirteenActionPerformed

    private void fifteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fifteenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_fifteenActionPerformed

    private void sixteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixteenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_sixteenActionPerformed

    private void fourteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourteenActionPerformed
        setInputDisplay(evt);
    }//GEN-LAST:event_fourteenActionPerformed

    private void setInputDisplay(java.awt.event.ActionEvent evt){
        sudokuUI.setInput(evt.getActionCommand(), block, inputButton);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eight;
    private javax.swing.JButton eleven;
    private javax.swing.JButton fifteen;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton fourteen;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sixteen;
    private javax.swing.JButton ten;
    private javax.swing.JButton thirteen;
    private javax.swing.JButton three;
    private javax.swing.JButton twelve;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
